"""
mixing_network.py — QMIX Mixing Network
========================================
Pseudocode level: 4/10 (conceptual structure, no specific dimensions or activations)

The mixing network takes the individual agent Q-values [Q₀, Q₁] and
a jointly-observed state z, and produces a single global team value Q_tot.

The mixing function:
    Q_tot = fmix([Q₀, Q₁] ; z)

where fmix is a small neural network whose weights are generated
dynamically by hypernetworks conditioned on z.

Monotonicity constraint:
    ∂Q_tot/∂Qᵢ > 0 for all i

This is the Individual-Global-Max (IGM) property in practice.
It means: if agent i increases its utility for its chosen action,
the global team value can only increase — never decrease.
This allows decentralized greedy execution to be globally optimal.
"""

from hypernetworks import (
    HypernetworkFirstLayerWeights,
    HypernetworkFirstLayerBias,
    HypernetworkSecondLayerWeights,
    HypernetworkSecondLayerBias,
)


class QMIXMixingNetwork:
    """
    QMIX mixing network.

    Input:  individual Q-values [Q₀, Q₁], centralized joint state z
    Output: scalar Q_tot per batch item

    Architecture (two mixing layers):
        Layer 1: Q-values → hidden representation (via W₁·[Q₀,Q₁] + B₁, then activation)
        Layer 2: hidden → scalar (via W₂·h + B₂, no activation)

    All weights are generated by hypernetworks conditioned on z.
    Weight positivity is enforced by the hypernetworks (Softplus).
    Only weights need positivity — biases are unconstrained.
    """

    def __init__(self, joint_state_dim, num_agents, hidden_dim):
        """
        joint_state_dim: dimension of the concatenated joint state z
        num_agents: number of cooperating agents (determines input size)
        hidden_dim: width of the hidden layer inside the mixing network
        """
        # Four hypernetworks: two weight generators, two bias generators
        self.hypernet_w1 = HypernetworkFirstLayerWeights(joint_state_dim, hidden_dim, num_agents)
        self.hypernet_b1 = HypernetworkFirstLayerBias(joint_state_dim, hidden_dim)
        self.hypernet_w2 = HypernetworkSecondLayerWeights(joint_state_dim, hidden_dim)
        self.hypernet_b2 = HypernetworkSecondLayerBias(joint_state_dim)

    def forward(self, agent_q_values, joint_state):
        """
        Compute Q_tot from individual Q-values and joint state.

        agent_q_values: (batch_size, num_agents)
            — the Q-value for the action each agent took
            — typically gathered from agent DQNs using the actions stored in replay buffer

        joint_state: (batch_size, joint_state_dim)
            — centralized information: [s₀; s₁] concatenated
            — ONLY available during training, not execution

        returns: (batch_size,) — one Q_tot per transition in the batch
        """
        batch_size = get_batch_size(agent_q_values)

        # Reshape Q-values to (batch_size, num_agents, 1) for batch matrix multiply
        q_vec = reshape(agent_q_values, shape=(batch_size, num_agents, 1))

        # ── Layer 1: Q-values → hidden representation ────────────────────────
        # Get weights and bias from hypernetworks
        W1 = self.hypernet_w1.forward(joint_state)  # (batch_size, hidden_dim, num_agents)
        B1 = self.hypernet_b1.forward(joint_state)  # (batch_size, 1, hidden_dim)

        # Batch matrix multiply: W1 @ q_vec
        # (batch_size, hidden_dim, num_agents) @ (batch_size, num_agents, 1)
        # → (batch_size, hidden_dim, 1)
        hidden = batch_matrix_multiply(W1, q_vec)

        # Add bias (broadcasts over hidden_dim dimension)
        hidden = hidden + transpose(B1)  # shape: (batch_size, hidden_dim, 1)

        # Apply intermediate activation (smooth, supports negative inputs)
        # ELU used here rather than ReLU to avoid dead neurons
        hidden = smooth_nonlinear_activation(hidden)  # (batch_size, hidden_dim, 1)

        # ── Layer 2: hidden → scalar Q_tot ──────────────────────────────────
        # Get weights and bias from hypernetworks
        W2 = self.hypernet_w2.forward(joint_state)  # (batch_size, 1, hidden_dim)
        B2 = self.hypernet_b2.forward(joint_state)  # (batch_size, 1, 1)

        # Batch matrix multiply: W2 @ hidden
        # (batch_size, 1, hidden_dim) @ (batch_size, hidden_dim, 1) → (batch_size, 1, 1)
        q_tot = batch_matrix_multiply(W2, hidden) + B2  # (batch_size, 1, 1)

        # Squeeze to (batch_size,) — one scalar Q_tot per transition
        q_tot = squeeze(q_tot)
        return q_tot

    def verify_monotonicity(self, agent_q_values, joint_state, agent_index):
        """
        Diagnostic check: verify that Q_tot is increasing in Q_i.
        Perturb Q_i by a small positive delta and confirm Q_tot increases.

        This should ALWAYS hold by construction (Softplus weights guarantee it).
        Useful for debugging if training behaves unexpectedly.
        """
        q_base = self.forward(agent_q_values, joint_state)

        # Perturb agent_index Q-value upward
        q_perturbed = agent_q_values.clone()
        q_perturbed[:, agent_index] += small_positive_delta

        q_higher = self.forward(q_perturbed, joint_state)

        # Monotonicity holds if all values increased (or stayed the same)
        assert all(q_higher >= q_base), "Monotonicity violated — check Softplus enforcement"
